// Uncomment these imports to begin using these cool features!

// import {inject} from '@loopback/core';
import {get, param} from '@loopback/rest'

export class AutoGeneratedApiController {
  constructor() {}

  @get('/hello')
  hello():String {
    return "Hello World! This endpoint is generated using Loopback 4!"
  }

  @get('/echo')
  echo(@param.query.string('msg') msg:string):String {
    return 'Echoing this message back to you - '+msg;
  }

}
